### ISSUE TITLE
Why is there a data.js file and a data.ts file?

### ISSUE THREAD

**Issue by mrajcok** [driftyco/ionic2-starter-tabs#3]
Was the app/data/data.js file submitted by accident?  It looks like a transpiled version of data.ts.

**Comment by mlynch** [comment]
It's been removed, but we are deleting this repo soon because it doesn't follow our best practices nor is it necessary given our new scaffolding system

**Comment by tlancina** [comment]
Hey apologies for the confusion, a lot of the starter workflow is heavily in flux at the moment as we discuss the easiest way for people to get up and running.

I'm going to move the .ts files to .js in the meantime to be more in line with our other starters, although we may convert them all to TS.

**Comment by tlancina** [comment]
To further clarify, this is staying open because while you can scaffold a child page with tabs using `ionic g tabs TabsPage`, it won't be your root page (`@App`).  

For root navigation like tabs or sidemenu you still do `ionic start MyApp tabs` like v1 :)

**Comment by mrajcok** [comment]
Thanks for the clarification, that helped, since I'm new to Ionic.  I was not aware of the cli generate feature.

I'd rather have the .ts files.  One reason is because with .js files and Visual Studio Code I get the following error on the decorators: This can only be used with ES6. Make sure to have a jsconfig.json-file which sets the target to ES6.  Is there any documentation explaining how to configure VS Code with Ionic 2 projects?

**Comment by ch-weiss** [comment]
Thanks for the Information. Unfortunately this is no good news for me. Is there any support for developing in TS? If not when will TS be supported , e.g. by generating TS starters?

**Comment by mlynch** [comment]
It'll work fine, we are just not forcing it through our starters. We will have a normal TS usage story, so no worries there.

Tim I'm closing because it's not actionable right now. Let's create separate issues for the individual points here.
